version = 1

[envs.tmux]
channels = ["conda-forge"]
dependencies = { tmux = "*" }
exposed = { tmux = "tmux" }

[envs.nodejs]
channels = ["conda-forge"]
dependencies = { nodejs = "*" }
exposed = { corepack = "corepack", node = "node", npm = "npm", npx = "npx" }

[envs.git]
channels = ["conda-forge"]
dependencies = { git = "*" }
exposed = { git = "git", git-cvsserver = "git-cvsserver", git-receive-pack = "git-receive-pack", git-shell = "git-shell", git-upload-archive = "git-upload-archive", git-upload-pack = "git-upload-pack", gitk = "gitk", scalar = "scalar" }

[envs.curl]
channels = ["conda-forge"]
dependencies = { curl = "*" }
exposed = { curl = "curl" }

[envs.yarn]
channels = ["conda-forge"]
dependencies = { yarn = "*" }
exposed = { yarn = "yarn", "yarn.cmd" = "yarn.cmd", "yarn.js" = "yarn.js", "yarn.ps1" = "yarn.ps1" }

[envs.python]
channels = ["conda-forge"]
dependencies = { python = "3.10.*" }
exposed = { 2to3 = "2to3", "2to3-3.10" = "2to3-3.10", idle3 = "idle3", "idle3.10" = "idle3.10", pydoc = "pydoc", pydoc3 = "pydoc3", "pydoc3.10" = "pydoc3.10", python = "python", python3 = "python3", python3-config = "python3-config", "python3.1" = "python3.1", "python3.10" = "python3.10", "python3.10-config" = "python3.10-config" }

[envs.pip]
channels = ["conda-forge"]
dependencies = { pip = "*" }
exposed = { pip = "pip", pip3 = "pip3" }

[envs.jedi]
channels = ["conda-forge"]
dependencies = { jedi = "*" }
